name: My first Yaml

on: [push]

jobs:
  job 1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Step one of job 1
      uses: actions/checkout@v2
    - name: Step two of job 1
      run: env | sort

  job 2:
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Step one of job 2
      uses: actions/checkout@v2
    - name: Step two of job 2
      run: "Get-ChildItem Env: | Sort-Object Name"

