name: hello python

on: [push]

env:
    Artifacte_name: MyArtifcatName

jobs:
    Test:
        name: Test the repo
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Run all tests
          run: python hello.py
    Build:
        name: Build the repo
        needs: [Test]
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Create an artifact
          uses: actions/upload-artifact@v2
          with:
            name: ${{ env.Artifacte_name }}
            path: .

